// Code generated by "stringer -type=FnfKey"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoteKeyLeft0-0]
	_ = x[NoteKeyLeft1-1]
	_ = x[NoteKeyDown0-2]
	_ = x[NoteKeyDown1-3]
	_ = x[NoteKeyUp0-4]
	_ = x[NoteKeyUp1-5]
	_ = x[NoteKeyRight0-6]
	_ = x[NoteKeyRight1-7]
	_ = x[SelectKey-8]
	_ = x[PauseKey-9]
	_ = x[EscapeKey-10]
	_ = x[NoteScrollUpKey-11]
	_ = x[NoteScrollDownKey-12]
	_ = x[AudioSpeedUpKey-13]
	_ = x[AudioSpeedDownKey-14]
	_ = x[SongResetKey-15]
	_ = x[SetBookMarkKey-16]
	_ = x[JumpToBookMarkKey-17]
	_ = x[ZoomOutKey-18]
	_ = x[ZoomInKey-19]
	_ = x[ToggleDebugKey-20]
	_ = x[ToggleLogNoteEvent-21]
	_ = x[ReloadAssetsKey-22]
	_ = x[FnfKeySize-23]
}

const _FnfKey_name = "NoteKeyLeft0NoteKeyLeft1NoteKeyDown0NoteKeyDown1NoteKeyUp0NoteKeyUp1NoteKeyRight0NoteKeyRight1SelectKeyPauseKeyEscapeKeyNoteScrollUpKeyNoteScrollDownKeyAudioSpeedUpKeyAudioSpeedDownKeySongResetKeySetBookMarkKeyJumpToBookMarkKeyZoomOutKeyZoomInKeyToggleDebugKeyToggleLogNoteEventReloadAssetsKeyFnfKeySize"

var _FnfKey_index = [...]uint16{0, 12, 24, 36, 48, 58, 68, 81, 94, 103, 111, 120, 135, 152, 167, 184, 196, 210, 227, 237, 246, 260, 278, 293, 303}

func (i FnfKey) String() string {
	if i < 0 || i >= FnfKey(len(_FnfKey_index)-1) {
		return "FnfKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FnfKey_name[_FnfKey_index[i]:_FnfKey_index[i+1]]
}
